name: Warmer LinkedIn Chrome Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-upload:
    name: Build and Upload Extension
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Create the zip file
      - name: Zip Chrome Extension
        run: |
          mkdir -p build
          zip -r build/extension.zip . -x '.git*' -x 'node_modules/*'
      
      # Step 3: Debug build directory (verify files)
      - name: Verify Build Directory
        run: ls -R build

      # Step 4: Generate build metadata
      - name: Create Build Metadata Files
        run: |
          echo "${{ github.sha }}" > build/build-commit
          echo "${{ github.run_number }}" > build/build-num
      
      # Step 5: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 6: Upload to Google Cloud Storage
      - name: Upload to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: build/*
          destination: chrome-extension/
          gzip: true

      # Step 7: Debug successful upload
      - name: Confirm Upload Success
        run: echo "Upload completed successfully."
