name: Warmer LinkedIn Chrome Extension

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    name: Build and Upload Extension
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Create the zip file
      - name: Zip Chrome Extension
        run: |
          mkdir -p build
          zip -r build/extension.zip . -x '.git*' -x 'node_modules/*'

      # Step 3: Generate build metadata
      - name: Create Build Metadata Files
        run: |
          echo "${{ github.sha }}" > build/build-commit
          echo "${{ github.run_number }}" > build/build-num

      # Step 4: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 5: Upload to Google Cloud Storage
      - name: Upload to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          bucket: ${{ env.GCS_BUCKET_NAME }}
          source: build/*
          destination: chrome-extension/

