name: Warmer LinkedIn Chrome Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-upload:
    name: Build and Upload Extension
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Create the zip file
      - name: Zip Chrome Extension
        run: |
          mkdir -p build
          zip -r build/extension.zip . -x '.git*' -x 'node_modules/*'
          if [ ! -f build/extension.zip ]; then
            echo "Error: ZIP file was not created."
            exit 1
          fi

      # Step 3: Verify the build directory
      - name: Verify Build Directory
        run: |
          echo "Listing build directory contents:"
          ls -la build

      # Step 4: Generate build metadata
      - name: Create Build Metadata Files
        run: |
          git rev-list --format=%B -n 1 HEAD > build/build-commit
          echo "build:1.0.${{ github.run_number }}" > build/build-num

      # Step 5: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 6: Upload to Google Cloud Storage
      - name: Upload to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: build/extension.zip
          destination: warmer-extension/
          gzip: true

      - name: Upload build-commit to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: build/build-commit
          destination: warmer-extension
          
      - name: Upload build-num to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: build/build-num
          destination: warmer-extension

      # Step 7: Confirm successful upload
      - name: Confirm Upload Success
        run: echo "Upload completed successfully."
